version: '3.8'

services:
  licitaciones-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: gestion-licitaciones-app:latest
    container_name: gestion-licitaciones-api
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=licitaciones-db;Port=5432;Database=LicitacionesDb;Username=postgres;Password=postgres
    depends_on:
      - licitaciones-db

  licitaciones-db:
    image: postgres:16-alpine
    container_name: licitaciones-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=LicitacionesDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: