services:
  licitaciones-api:
    image: licitaciones-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=LicitacionesDb;Username=postgres;Password=Eren2004
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: postgres_licitaciones
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Eren2004
      - POSTGRES_DB=LicitacionesDb
    ports:
      - "5433:5432" # Expone el 5432 interno hacia el 5433 del host
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: