apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: licitaciones-namespace
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Database=LicitacionesDb;Username=postgres;Password=Eren2004"