apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: licitaciones-namespace
type: Opaque
data:
  # licitaciones_password123 en Base64 -> bGljaXRhY2lvbmVzX3Bhc3N3b3JkMTIz
  POSTGRES_PASSWORD: "bGljaXRhY2lvbmVzX3Bhc3N3b3JkMTIz"
  # Host=postgres-service;Database=LicitacionesDb;Username=licitaciones_user;Password=licitaciones_password123
  ConnectionStrings__DefaultConnection: "SG9zdD1wb3N0Z3Jlcy1zZXJ2aWNlO0RhdGFiYXNlPUxpY2l0YWNpb25lc0RiO1VzZXJuYW1lPWxpY2l0YWNpb25lc191c2VyO1Bhc3N3b3JkPWxpY2l0YWNpb25lc19wYXNzd29yZDEyMw=="