apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: licitaciones-namespace
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  POSTGRES_DB: "LicitacionesDb"
  POSTGRES_USER: "licitaciones_user"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"