name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar la solucion
        run: dotnet build --no-restore --configuration Release

      - name: Ejecutar pruebas
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Construir imagen Docker
        run: docker build -t licitaciones-app:latest .

      - name: Validar Kubernetes
        run: kubectl apply --dry-run=client -f k8s/